#ifndef __INCGUARD_DEFS__
#define __INCGUARD_DEFS__
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ start ~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
#define VERSION "0.02"
#define gfx_SetPaletteEntry(offset,color1555) ((uint16_t*)0xE30200)[offset] = color1555;
#define abs(x) ((x<0)?(-x):x)
#define CLIPPING 1
/* ------------------------------ Colors -------------------------- */
#define COLOR_BLACK				0
#define COLOR_WHITE				1
#define COLOR_RED				2
#define COLOR_GREEN				3
#define COLOR_BLUE				4
#define COLOR_TRANS				5
#define COLOR_GRAY				6
#define COLOR_LIGHTGRAY			7
#define COLOR_GUNMETALGRAY		8
#define COLOR_GOLD				9
#define COLOR_CYAN				10
#define COLOR_LIME				11
#define COLOR_ORANGE			12
#define COLOR_FORESTGREEN		13
#define COLOR_DARKGRAY			14
#define COLOR_PURPLE			15
/* ------------------------------ Keyboard ------------------------ */
#define kbit_Down		(1<<0)
#define kbit_Left		(1<<1)
#define kbit_Right		(1<<2)
#define kbit_Up			(1<<3)
#define kbit_Alpha		(1<<4)
#define kbit_2nd		(1<<5)
#define kbit_Mode		(1<<6)
#define kbit_Del		(1<<7)
/* --------------------------- Game State ------------------------- */
#define GS_TITLE	0
#define GS_NEWGAME	(GS_TITLE+1)
#define GS_LOADGAME	(GS_TITLE+2)
#define GS_CREDITS	(GS_TITLE+3)
#define GS_QUIT		(GS_TITLE+4)
#define GS_GAMEMODE	32
#define GS_MENUMODE	64
/* ----------------------- Enemy Sprite Redefs -------------------- */
#define S_NULL		&(tiles[0])
#define S_NORMRAT	&(characters_tiles_data[0])
#define S_DIRERAT	&(characters_tiles_data[2])
#define S_SQUIRREL	&(characters_tiles_data[4])
#define S_SNAKE		&(characters_tiles_data[6])
#define S_LIZARD	&(characters_tiles_data[8])
#define S_TURTLE	&(characters_tiles_data[10])
#define S_LIZMAN	&(characters_tiles_data[12])
#define S_HIDDEN	&(characters_tiles_data[14])
#define S_ASP		&(characters_tiles_data[16])
#define S_HYDRA		&(characters_tiles_data[18])
#define S_WISP		&(characters_tiles_data[20])
#define S_BEAN		&(characters_tiles_data[22])
#define S_SKEL		&(characters_tiles_data[24])
#define S_ZOMBIE	&(characters_tiles_data[26])
#define S_ZOMBONE	&(characters_tiles_data[28])
#define S_REAPER	&(characters_tiles_data[30])
#define S_NECRO		&(characters_tiles_data[32])
#define S_SHADE		&(characters_tiles_data[34])
#define S_SCORPION	&(characters_tiles_data[36])
#define S_LADYBUG	&(characters_tiles_data[38])
#define S_SHARK		&(characters_tiles_data[40])
#define S_FISH		&(characters_tiles_data[42])
#define S_BAT		&(characters_tiles_data[44])
#define S_SWAN		&(characters_tiles_data[46])
#define S_PARROT	&(characters_tiles_data[48])
#define S_CHICKEN	&(characters_tiles_data[50])
#define S_DOGGO		&(characters_tiles_data[52])
#define S_DOGMAN	&(characters_tiles_data[54])
#define S_LIGHTS	&(characters_tiles_data[56])
#define S_DARKS		&(characters_tiles_data[58])
#define S_OHDEER	&(characters_tiles_data[60])
#define S_BADOAK	&(characters_tiles_data[62])
#define S_BADPINE	&(characters_tiles_data[64])
#define S_GOBSTER	&(characters_tiles_data[66])
#define S_APE		&(characters_tiles_data[68])
#define S_SMILES	&(characters_tiles_data[70])
#define S_FAE		&(characters_tiles_data[72])
#define S_BADCOP	&(characters_tiles_data[74])
#define S_ANGEL		&(characters_tiles_data[76])
#define S_KING		&(characters_tiles_data[78])
#define S_PLAYER0	&(player0_tiles_data[0])
/* ------------------- Mobile Object Definitions ------------------ */
#define MOB_NORMRAT		1
#define MOB_DIRERAT		2
#define MOB_SQUIRREL	3
#define MOB_SNAKE		4
#define MOB_LIZARD		5
#define MOB_TURTLE		6
#define MOB_LIZMAN		7
#define MOB_HIDDEN		8
#define MOB_ASP			9
#define MOB_HYDRA		10
#define MOB_WISP		11
#define MOB_BEAN		12
#define MOB_SKEL		13
#define MOB_ZOMBIE		14
#define MOB_ZOMBONE		15
#define MOB_REAPER		16
#define MOB_NECRO		17
#define MOB_SHADE		18
#define MOB_SCORPION	19
#define MOB_LADYBUG		20
#define MOB_SHARK		21
#define MOB_FISH		22
#define MOB_BAT			23
#define MOB_SWAN		24
#define MOB_PARROT		25
#define MOB_CHICKEN		26
#define MOB_DOGGO		27
#define MOB_DOGMAN		28
#define MOB_LIGHTS		29
#define MOB_DARKS		30
#define MOB_OHDEER		31
#define MOB_BADOAK		32
#define MOB_BADPINE		33
#define MOB_GOBSTER		34
#define MOB_APE			35
#define MOB_SMILES		36
#define MOB_FAE			37
#define MOB_BADCOP		38
#define MOB_ANGEL		39
#define MOB_KING		40
//Up to ten classes. Seems like overkill.
#define MOB_PLAYER0		245
#define MOB_PLAYER1		246
/* ------------------- Mobile Object State Flags ------------------ */
#define MSTAT_SPOTTED	(1<<0)
#define MSTAT_ISMOVING  (1<<1)
#define MSTAT_RESERVED2 (1<<2)
#define MSTAT_RESERVED3 (1<<3)
#define MSTAT_RESERVED4 (1<<4)
#define MSTAT_RESERVED5 (1<<5)
#define MSTAT_RESERVED6 (1<<6)
#define MSTAT_RESERVED7 (1<<7)
/* ----------------------- Sidebar Update Flags ------------------- */
#define UPD_XP			(1<<0)
#define UPD_FOOD		(1<<1)
#define UPD_MINI		(1<<2)
#define UPD_HP			(1<<3)
#define UPD_MP			(1<<4)
#define UPD_CURGEAR		(1<<5)
#define UPD_QUICKSET	(1<<6)
#define UPD_BACKERS		(1<<7)
#define UPD_SIDEBAR		0xFF
/* -------------------- Dungeon generator defines ----------------- */
#define NUMROOMS_MAX 30
#define AREAHIMASK 0xE0
#define AREALOMASK 0x1F
#define AREAHICONV(x) ((x&0x07)<<5)
#define AREAHIUNCONV(x) ((x>>5)&0x07)
#define AREA_FOREST AREAHICONV(0)
#define AREA_DUNGEON1 AREAHICONV(1)
#define AREA_DUNGEON2 AREAHICONV(2)
#define AREA_DUNGEON3 AREAHICONV(3)
#define AREA_DUNGEON4 AREAHICONV(4)
#define AREA_DUNGEON5 AREAHICONV(5)
#define FEX_WEST      (1<<0)
#define FEX_EAST      (1<<1)
#define FEX_SOUTH     (1<<2)
#define FEX_NORTH     (1<<3)
#define FEX_EXIT      (1<<4)
#define FEX_DUNGEON   (1<<5)
#define FEX_FLOORUP   (1<<6)
#define FEX_FLOORDOWN (1<<7)
/* -------------------------- Item type defines ------------------- */
#define EFL_RNG (1<<0)
#define EFL_HAT (1<<1)
#define EFL_ARM (1<<2)
#define EFL_GLO (1<<3)
#define EFL_WPN (1<<4)
#define EFL_BTS (1<<5)
#define EFL_2ND (1<<6)
#define EFL_MSC (1<<7)
#define ITEM_EQUIPPABLE	1
#define EQU_ROBE			1
#define EQU_LEATHERARMOR	2
#define EQU_METALARMOR		3
#define EQU_REFLECTARMOR	4
#define EQU_INTPENDANT		5
#define EQU_STRPENDANT		6
#define EQU_AGIPENDANT		7
#define EQU_MPPENDANT		8
#define EQU_HPPENDANT		9
#define EQU_DEFPENDANT		10
#define EQU_REFLECTPENDANT	11
#define EQU_ALLMIGHTPENDANT	12
#define EQU_MDEFRING		13
#define EQU_ELECDEFRING		14
#define EQU_FIREDEFRING		15
#define EQU_POISONDEFRING	16
#define EQU_STRRING			17
#define EQU_DEFRING			18
#define EQU_MPRING			19
#define EQU_SNEAKRING		20
#define EQU_ATKRING			21
#define EQU_MAGRING			22
#define EQU_HPRING			23
#define EQU_RAWRSRING		24
#define EQU_REFLECTRING		25
#define EQU_UNUSEDRING1		26
#define EQU_UNUSEDRING2		27
#define EQU_WALLRING		28
#define EQU_SHOES			29
#define EQU_BOOTS			30
#define EQU_METALBOOTS		31
#define EQU_NINJABOOTS		32
#define EQU_LEATHERCAP		33
#define EQU_HAT				34
#define EQU_METALHAT		35
#define EQU_REFLECTHAT		36
#define EQU_THIEFGLOVE		37
#define EQU_LEATHERGLOVE	38
#define EQU_BATTLEMITTS		39
#define EQU_BADTOUCHER		40
#define EQU_BUCKLER			41
#define EQU_SMALLSHIELD		42
#define EQU_TOWERSHIELD		43
#define EQU_REFLECTSHIELD	44
#define EQU_MAGICMISSILE	45
#define EQU_LIGHTNING		46
#define EQU_FIREBALL		47
#define EQU_POISONBOLT		48
#define EQU_SHORTSWORD		49
#define EQU_LONGSWORD		50
#define EQU_BUSTERSWORD		51
#define EQU_SHADOWSWORD		52
#define EQU_MININGPICK		53
#define EQU_LONGAXE			54
#define EQU_HALBERD			55
#define EQU_SPEAR			56
#define EQU_SAFTEYGOGGLES	57
#define EQU_PRAYERBEADS		58
#define EQU_CRYSTALBALL		59
#define EQU_ESCAPEROPE		60
#define EQU_SHORTBOW		61
#define EQU_LONGBOW			62
#define EQU_SLING			63
#define EQU_HANDRIFLE		64
#define EQU_EQUIPPABLE_END	65
#define ITEM_CONSUMABLE 192
#define CONS_BLINK			192
#define CONS_CHAINLIGHTNING	193
#define CONS_HELLFIRE		194
#define CONS_ACQUIREMENT	195
#define CONS_HEALTH			196
#define CONS_MANA			197
#define CONS_EXPERIENCE		198
#define CONS_REGENERATION	199
#define CONS_FARSIGHT		200
#define CONS_BLOODTHIRST	201
#define CONS_IRONHIDE		202
#define CONS_LOUDERRAWRS	203
#define CONS_UNUSEDPOTION1	204
#define CONS_UNUSEDPOTION2	205
#define CONS_UNUSEDPOTION3	206
#define CONS_UNUSEDPOTION4	207
#define CONS_UNUSEDWAND1	208
#define CONS_UNUSEDWAND2	209
#define CONS_UNUSEDWAND3	210
#define CONS_UNUSEDWAND4	211
#define CONS_UNUSEDWAND5	212
#define CONS_UNUSEDWAND6	213
#define CONS_UNUSEDWAND7	214
#define CONS_UNUSEDWAND8	215
#define CONS_CONSUMABLE_END	216
#define KITEM_MCGUFF1		(1<<0)
#define KITEM_MCGUFF2		(1<<1)
#define KITEM_MCGUFF3		(1<<2)
#define KITEM_MCGUFF4		(1<<3)
#define KITEM_LCHERRY		(1<<4)
//Do not add any more mcguffins or cherry gate will break
/* ---------------------- Static object defines ------------------- */
#define SOBJTMSKLO 0x07
#define SOBJTMSKHI 0x78
#define SOBJTYPECAT(x) (x<<3)
#define SOBJ_DOORBASE SOBJTYPECAT(0)
#define SOBJ_DOOR		SOBJ_DOORBASE+0
#define SOBJ_LOCKDOOR	SOBJ_DOORBASE+1
#define SOBJ_MLOKDOOR	SOBJ_DOORBASE+2
#define SOBJ_TIMEDOOR	SOBJ_DOORBASE+3
#define SOBJ_BOSSDOOR	SOBJ_DOORBASE+4
#define SOBJ_SW1DOOR	SOBJ_DOORBASE+5
#define SOBJ_SW2DOOR	SOBJ_DOORBASE+6
#define SOBJ_SW3DOOR	SOBJ_DOORBASE+7
#define SOBJ_WARPBASE SOBJTYPECAT(1)
#define SOBJ_WARPHIDDEN	SOBJ_WARPBASE+0
#define SOBJ_WARPGATE	SOBJ_WARPBASE+1
#define SOBJ_WARPPAD	SOBJ_WARPBASE+2
#define SOBJ_WARPGATE2	SOBJ_WARPBASE+3
#define SOBJ_STAIRSUP	SOBJ_WARPBASE+4
#define SOBJ_STAIRSDOWN	SOBJ_WARPBASE+5
#define SOBJ_TRAPBASE SOBJTYPECAT(2)
#define SOBJ_TRAPSPIKES	SOBJ_TRAPBASE+0
#define SOBJ_TRAPSTICKS	SOBJ_TRAPBASE+1
#define SOBJ_TELEPORTER	SOBJ_TRAPBASE+2
#define SOBJ_TRAPPIT	SOBJ_TRAPBASE+3
#define SOBJ_CHESTBASE SOBJTYPECAT(3)
#define SOBJ_NORMCHEST	SOBJ_CHESTBASE+0
#define SOBJ_LOCKCHEST	SOBJ_CHESTBASE+1
#define SOBJ_MLOKCHEST	SOBJ_CHESTBASE+2
#define SOBJ_CRYSCHEST	SOBJ_CHESTBASE+3
#define SOBJ_FAKECHEST	SOBJ_CHESTBASE+4
#define SOBJ_ITEMBASE SOBJTYPECAT(4)
#define SOBJ_MONEY		SOBJ_ITEMBASE+0
#define SOBJ_OPTIONALS	SOBJ_ITEMBASE+1
#define SOBJ_MCGUFFIN	SOBJ_ITEMBASE+2
#define SOBJ_HIDDENKITM	SOBJ_ITEMBASE+3
#define SOBJ_FOOD		SOBJ_ITEMBASE+4
#define SOBJ_MOARFOOD	SOBJ_ITEMBASE+5
#define SOBJ_CHERRY		SOBJ_ITEMBASE+6

/* ------------- Tile mapping and tile identity defines ----------- */
#define wallAbase	( 0+(0*18))
#define wallBbase	( 0+(1*18))
#define wallCbase	( 0+(2*18))
#define floorAbase	(64+(0*21))
#define floorBbase	(64+(1*21))
#define floorCbase	(64+(2*21))
#define FLOORBASE 		0x80
#define floortilebase	0x80
//Offset+1 = trap activated
#define TILE_TRAP1	(FLOORBASE+0)
#define TILE_TRAP2	(FLOORBASE+2)
#define TILE_TRAP3	(FLOORBASE+4)
#define TILE_TRAP4	(FLOORBASE+6)
#define TILE_TRAP5	(FLOORBASE+8)
#define TILE_TRAP6	(FLOORBASE+10)
#define TILE_TRAP7	(FLOORBASE+12)
//Offset+1 = door embedded in a vertical wall (side-view)
#define TILE_DOOROPEN	(FLOORBASE+14)
#define TILE_DOORCLOSED	(FLOORBASE+16)
#define TILE_DOORLOCKED	(FLOORBASE+18)
#define TILE_DOORSEALED	(FLOORBASE+20)
//Offset+0 = portal disabled, Offsets +1 and +2 = portal active animation frames
#define TILE_PORTAL1	(FLOORBASE+22)
#define TILE_PORTAL2	(FLOORBASE+25)
#define TILE_STAIRSUP	(FLOORBASE+28)
#define TILE_STAIRSDOWN	(FLOORBASE+29)
#define TILE_STAIRSBIGUP	(FLOORBASE+30)
#define TILE_STAIRSBIGDOWN	(FLOORBASE+31)
//Offset+0 = chest closed, +1 = opened
#define TILE_TREASURECHEST	(FLOORBASE+32)
#define TILE_TREASURELOCKED	(FLOORBASE+34)
#define TILE_TREASURESEALED	(FLOORBASE+36)
#define TILE_CRYSTALTREASURE	(FLOORBASE+38)
//Misc
#define TILE_MONEYBIG		(FLOORBASE+40)
#define TILE_MONEYMED		(FLOORBASE+41)
#define TILE_MONEYSMOL		(FLOORBASE+42)
#define TILE_KEY			(FLOORBASE+43)
#define TILE_MASTERKEY		(FLOORBASE+44)
#define TILE_LAMP			(FLOORBASE+45)
#define TILE_KEYCARD		(FLOORBASE+46)
#define TILE_CANDLES		(FLOORBASE+47)
//------------
#define KITEMBASE 0xC0
#define kitembase (128+64)
//Key items and foods. All with animations are +1 offset.
#define TILE_MCGUFFIN1 (KITEMBASE+0)
#define TILE_MCGUFFIN2 (KITEMBASE+2)
#define TILE_MCGUFFIN3 (KITEMBASE+4)
#define TILE_MCGUFFIN4 (KITEMBASE+6)
#define TILE_SMOLFOOD  (KITEMBASE+8)
#define TILE_MOREFOOD  (KITEMBASE+9)
#define TILE_BIGFOOD   (KITEMBASE+10)
#define TILE_ISSAFEAST (KITEMBASE+11)
#define TILE_LCHERRY   (KITEMBASE+12)




#endif